---
abstract: 'Look up Canadian Federal Sales Tax rates'
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  English: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CA-GST
requires:
  Moose: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-CA-GST
  repository: http://hg.urth.org/hg/Markdent
version: 0.01
